include: package:surf_lint_rules/analysis_options.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/assets/images/**
    - lib/assets/strings/**

formatter:
  page_width: 120


dart_code_metrics:
  extends:
    - package:surf_dcm_presets/all.yaml
  rules:
    - avoid-nullable-interpolation: false
    - prefer-correct-callback-field-name: false
    - avoid-unnecessary-stateful-widgets: false
    - avoid-shadowing:
        ignored-names:
          - context
    - prefer-correct-identifier-length:
        exceptions: [ "a", "b", "i", "j", "k", "p", "c", "e", "s" ]
        max-identifier-length: 30
        min-identifier-length: 2
    - member-ordering:
        alphabetize: false
        order:
          - static-fields
          - static-methods

          - private-fields
          - public-fields

          - constructors
          - named-constructors
          - factory-constructors

          - public-getters-setters
          - public-methods

          - overridden-fields
          - overridden-getters-setters
          - overridden-methods

          - private-getters-setters
          - private-methods
        widgets-order:
          - const-fields
          - static-methods
          - final-fields
          - var-fields
          - constructor
          - named-constructor
          - init-state-method
          - did-change-dependencies-method
          - did-update-widget-method
          - dispose-method
          - build-method
          - private-methods
